### ISSUE TITLE
Time for standard convergence on the full Planck likelihood (TTTEEE)?

### ISSUE THREAD

**Issue by tsmith2** [PolyChord/PolyChordLite#68]
I running PolyChord on the full Planck likelihood (TTTEEE), and I am wondering if anyone can give me a sense of how long it should take to reach convergence (with the 'standard' parameters from Cobaya: `nlive: 25d` and `precision_criterion: 0.001`) for LCDM using 20 MPI processes (2 cores each process).

**Comment by lukashergt** [comment]
Hi @tsmith2 

Assuming the following setup:
* theory code CLASS version 2.9.4
* nonlinear code halofit
* cosmology is standard LCDM
* Planck likelihoods TTTEEE+lowl+lowE
* sampler PolyChord version 1.18.1 
* `ndim=6+1+20=27` sampling parameters and thus `25*27=675` live points
* `num_repeats=2d` with speed blocking of `1, 15, 15` and thus the PolyChord number of repeats are `12, 30, 600`
* 40 computing cores 
(Not sure what you mean by "2 cores each process", you should _not_ be using OpenMP when running with PolyChord...)

**In this case I'd expect a computing time of about `5d 5h = 125h`.**
Note that this is based on a very rough projection from my runs with different nlive and ncores.

---

Note:
* I don't recommend doing your first run with `nlive: 25d`! Start out with fewer live points, check that things look sensible, and only then set up the big runs with large number of live points.
* Using CAMB instead of CLASS seems to take half as long (no clue why... would love to find out).
* Using hmcode instead of halofit will take longer.
